name: dashwing
description: cli & static file server
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.3

dependencies:
  args: ^2.7.0
  async: ^2.13.0
  collection: ^1.19.1
  essential_dart: ^2.0.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  pedantic_mono: ^1.35.0
  test: ^1.25.6
